version: 2.1

jobs:

  example:
    docker:
      - image: circleci/android:api-26-node
    environment:
          ANDROID_BUILD_TOOLS_VERSION: 30.0.3
          ANDROID_HOME: ~/android-sdk
          PROGLOVE_URL: https://dl.cloudsmith.io/public/proglove/pgconnect-public/maven/

    steps:
      - checkout
      - run:
          name: Create android repository
          command: touch $HOME/.android/repositories.cfg
          
      - run:
          name: Fetch command line tools
          command: wget "https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip" -O commandlinetools.zip
          
      - run:
          name: Unzip command line tools
          command: unzip commandlinetools.zip
          
      - run:
          name: Gradle assemble debug
          command: ./gradlew assembleDebug

workflows:
  sample_workflow:
    jobs:
      - example
          


# VS Code Extension Version: 1.3.0